# Generated by Django 5.2.5 on 2025-08-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shredder', '0003_shredderinput'),
    ]

    operations = [
        migrations.CreateModel(
            name='tuningInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuning', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='shredderInput',
        ),
    ]
