# Generated by Django 5.2.5 on 2025-08-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shredder', '0004_tuninginput_delete_shredderinput'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuninginput',
            name='name',
            field=models.CharField(default='EADGBE', max_length=128),
        ),
    ]
