# Generated by Django 5.2.5 on 2025-08-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shredder', '0005_tuninginput_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tunings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
    ]
