# Generated by Django 5.2.5 on 2025-08-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shredder', '0006_tunings'),
    ]

    operations = [
        migrations.CreateModel(
            name='shredderInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accidentals', models.CharField(max_length=128)),
                ('key', models.CharField(max_length=128)),
                ('scale', models.CharField(max_length=128)),
                ('tuning', models.CharField(max_length=128)),
            ],
        ),
    ]
