# Generated by Django 5.2.5 on 2025-08-15 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shredder', '0007_shredderinput'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shredderinput',
            old_name='accidentals',
            new_name='accidental',
        ),
    ]
