# Generated by Django 5.2.5 on 2025-08-15 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shredder', '0008_rename_accidentals_shredderinput_accidental'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shredderinput',
            old_name='accidental',
            new_name='accidentals',
        ),
    ]
