# Generated by Django 5.2.5 on 2025-08-18 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shredder', '0009_rename_accidental_shredderinput_accidentals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shredderinput',
            old_name='accidentals',
            new_name='accidentals_defaults',
        ),
    ]
