# Generated by Django 5.2.5 on 2025-08-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shredder', '0010_rename_accidentals_shredderinput_accidentals_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
            ],
        ),
    ]
