# Generated by Django 5.2.5 on 2025-08-20 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shredder', '0011_mode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mode',
            new_name='Modes',
        ),
    ]
