# Generated by Django 5.2.5 on 2025-08-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shredder', '0012_rename_mode_modes'),
    ]

    operations = [
        migrations.AddField(
            model_name='shredderinput',
            name='mode',
            field=models.CharField(default='note', max_length=24),
        ),
        migrations.AlterField(
            model_name='shredderinput',
            name='tuning',
            field=models.CharField(default='EADGBE', max_length=128),
        ),
    ]
