# Generated by Django 5.2.5 on 2025-08-20 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shredder', '0014_alter_notes_accidentals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='accidentals',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accidentals', to='shredder.accidentals'),
        ),
    ]
